/**
 * Corporate partner data for the partner matching tool.
 * Each entry maps a company to the focus areas it actively supports,
 * the types of partnerships it offers, and a link to its giving/CSR page.
 */

export interface CorporatePartner {
  name: string
  slug: string
  description: string
  focusAreas: string[] // slugs from FOCUS_AREAS
  partnershipTypes: string[]
  givingUrl: string
  headquarters: string
  logo?: string
}

export const PARTNERSHIP_TYPES = [
  { value: 'grants', label: 'Direct Grants' },
  { value: 'sponsorship', label: 'Event & Program Sponsorship' },
  { value: 'in_kind', label: 'In-Kind Donations' },
  { value: 'employee_giving', label: 'Employee Giving & Matching' },
  { value: 'volunteer', label: 'Corporate Volunteerism' },
  { value: 'cause_marketing', label: 'Cause Marketing' },
  { value: 'tech_credits', label: 'Technology Credits' },
  { value: 'pro_bono', label: 'Pro Bono Services' },
  { value: 'collaborative_fund', label: 'Collaborative / Pooled Fund' },
  { value: 'intermediary', label: 'Intermediary Grantmaking' },
]

export const CORPORATE_PARTNERS: CorporatePartner[] = [
  {
    name: 'Google.org',
    slug: 'google-org',
    description: 'Supports nonprofits using technology to address global challenges in education, economic opportunity, and inclusion.',
    focusAreas: ['education', 'technology', 'economic-development', 'social-justice'],
    partnershipTypes: ['grants', 'tech_credits', 'employee_giving', 'pro_bono'],
    givingUrl: 'https://www.google.org/our-work/',
    headquarters: 'Mountain View, CA',
  },
  {
    name: 'Microsoft Philanthropies',
    slug: 'microsoft-philanthropies',
    description: 'Empowers nonprofits through technology grants, discounted software, and direct funding for social impact.',
    focusAreas: ['education', 'technology', 'workforce', 'disability'],
    partnershipTypes: ['grants', 'tech_credits', 'in_kind', 'employee_giving'],
    givingUrl: 'https://www.microsoft.com/en-us/philanthropies',
    headquarters: 'Redmond, WA',
  },
  {
    name: 'Salesforce Foundation',
    slug: 'salesforce-foundation',
    description: 'Leverages technology, people, and resources to improve communities through the 1-1-1 philanthropy model.',
    focusAreas: ['education', 'workforce', 'technology', 'community-development'],
    partnershipTypes: ['grants', 'tech_credits', 'volunteer', 'pro_bono'],
    givingUrl: 'https://www.salesforce.org',
    headquarters: 'San Francisco, CA',
  },
  {
    name: 'Amazon / AWS',
    slug: 'amazon-aws',
    description: 'Supports nonprofits through AWS cloud credits, direct grants, and the Amazon Future Engineer program.',
    focusAreas: ['education', 'technology', 'workforce', 'housing'],
    partnershipTypes: ['grants', 'tech_credits', 'in_kind', 'employee_giving'],
    givingUrl: 'https://aws.amazon.com/government-education/nonprofits/',
    headquarters: 'Seattle, WA',
  },
  {
    name: 'Bank of America',
    slug: 'bank-of-america',
    description: 'Invests in workforce development, community revitalization, and basic needs through philanthropy.',
    focusAreas: ['economic-development', 'housing', 'workforce', 'community-development'],
    partnershipTypes: ['grants', 'sponsorship', 'employee_giving', 'volunteer'],
    givingUrl: 'https://about.bankofamerica.com/en/making-an-impact/charitable-foundation-funding',
    headquarters: 'Charlotte, NC',
  },
  {
    name: 'JPMorgan Chase',
    slug: 'jpmorgan-chase',
    description: 'Drives inclusive economic growth through workforce development, small business support, and neighborhood revitalization.',
    focusAreas: ['economic-development', 'workforce', 'housing', 'community-development'],
    partnershipTypes: ['grants', 'sponsorship', 'employee_giving', 'volunteer'],
    givingUrl: 'https://www.jpmorganchase.com/impact',
    headquarters: 'New York, NY',
  },
  {
    name: 'Wells Fargo Foundation',
    slug: 'wells-fargo-foundation',
    description: 'Focuses on housing affordability, small business growth, and financial health for underserved communities.',
    focusAreas: ['housing', 'economic-development', 'community-development', 'education'],
    partnershipTypes: ['grants', 'sponsorship', 'employee_giving', 'volunteer'],
    givingUrl: 'https://www.wellsfargo.com/about/corporate-responsibility/',
    headquarters: 'San Francisco, CA',
  },
  {
    name: 'Patagonia',
    slug: 'patagonia',
    description: 'Supports grassroots environmental organizations working to protect and restore the natural environment.',
    focusAreas: ['environment', 'food-agriculture', 'community-development'],
    partnershipTypes: ['grants', 'in_kind', 'cause_marketing', 'employee_giving'],
    givingUrl: 'https://www.patagonia.com/how-we-fund/',
    headquarters: 'Ventura, CA',
  },
  {
    name: 'The Coca-Cola Foundation',
    slug: 'coca-cola-foundation',
    description: 'Supports community initiatives focused on water stewardship, women\'s empowerment, and education.',
    focusAreas: ['environment', 'education', 'social-justice', 'community-development'],
    partnershipTypes: ['grants', 'sponsorship', 'cause_marketing', 'volunteer'],
    givingUrl: 'https://www.coca-colacompany.com/social-impact',
    headquarters: 'Atlanta, GA',
  },
  {
    name: 'Target Foundation',
    slug: 'target-foundation',
    description: 'Invests in communities through grants focused on equity and inclusion, education, and basic needs.',
    focusAreas: ['education', 'social-justice', 'community-development', 'food-agriculture'],
    partnershipTypes: ['grants', 'sponsorship', 'volunteer', 'in_kind'],
    givingUrl: 'https://corporate.target.com/sustainability-ESG/communities',
    headquarters: 'Minneapolis, MN',
  },
  {
    name: 'Walmart Foundation',
    slug: 'walmart-foundation',
    description: 'Supports workforce development, economic opportunity, and sustainability in local communities.',
    focusAreas: ['workforce', 'economic-development', 'food-agriculture', 'community-development'],
    partnershipTypes: ['grants', 'sponsorship', 'volunteer', 'in_kind'],
    givingUrl: 'https://walmart.org/how-we-give/local-community-grants',
    headquarters: 'Bentonville, AR',
  },
  {
    name: 'Ben & Jerry\'s Foundation',
    slug: 'ben-jerrys-foundation',
    description: 'Supports grassroots organizing for social and environmental justice through small grants.',
    focusAreas: ['social-justice', 'environment', 'civic-engagement', 'community-development'],
    partnershipTypes: ['grants', 'cause_marketing'],
    givingUrl: 'https://www.benjerry.com/values/how-we-do-business/philanthropy',
    headquarters: 'South Burlington, VT',
  },
  {
    name: '3M Foundation',
    slug: '3m-foundation',
    description: 'Invests in STEM education, community development, and environmental stewardship.',
    focusAreas: ['education', 'science-research', 'environment', 'community-development'],
    partnershipTypes: ['grants', 'sponsorship', 'volunteer', 'in_kind'],
    givingUrl: 'https://www.3m.com/3M/en_US/gives-us/',
    headquarters: 'St. Paul, MN',
  },
  {
    name: 'General Mills Foundation',
    slug: 'general-mills-foundation',
    description: 'Strengthens communities through food access, sustainable agriculture, and hometown community investment.',
    focusAreas: ['food-agriculture', 'environment', 'community-development', 'education'],
    partnershipTypes: ['grants', 'sponsorship', 'volunteer', 'in_kind'],
    givingUrl: 'https://www.generalmills.com/how-we-make-it/community-impact',
    headquarters: 'Minneapolis, MN',
  },
  {
    name: 'Autodesk Foundation',
    slug: 'autodesk-foundation',
    description: 'Supports nonprofits using design and technology to create a more equitable, resilient, and sustainable world.',
    focusAreas: ['technology', 'environment', 'housing', 'community-development'],
    partnershipTypes: ['grants', 'tech_credits', 'pro_bono', 'in_kind'],
    givingUrl: 'https://www.autodesk.org',
    headquarters: 'San Francisco, CA',
  },
  {
    name: 'Zendesk Foundation',
    slug: 'zendesk-foundation',
    description: 'Supports tech-driven nonprofits removing barriers for underrepresented people through technology.',
    focusAreas: ['technology', 'social-justice', 'workforce', 'education'],
    partnershipTypes: ['grants', 'tech_credits', 'volunteer', 'pro_bono'],
    givingUrl: 'https://www.zendesk.com/company/social-impact/',
    headquarters: 'San Francisco, CA',
  },
  {
    name: 'UPS Foundation',
    slug: 'ups-foundation',
    description: 'Focuses on community safety, diversity, and the environment through volunteerism and grants.',
    focusAreas: ['community-development', 'environment', 'social-justice', 'health'],
    partnershipTypes: ['grants', 'volunteer', 'in_kind', 'employee_giving'],
    givingUrl: 'https://about.ups.com/us/en/social-impact/the-ups-foundation.html',
    headquarters: 'Atlanta, GA',
  },
  {
    name: 'Starbucks Foundation',
    slug: 'starbucks-foundation',
    description: 'Historically supports youth employment and community resilience. Note: significantly reduced charitable giving in 2025 due to shifting corporate budget priorities.',
    focusAreas: ['youth-development', 'veterans', 'workforce', 'community-development'],
    partnershipTypes: ['grants', 'volunteer', 'employee_giving', 'sponsorship'],
    givingUrl: 'https://www.starbucks.com/responsibility/community/starbucks-foundation',
    headquarters: 'Seattle, WA',
  },
  {
    name: 'Nike Foundation',
    slug: 'nike-foundation',
    description: 'Invests in getting kids moving through play, sport, and physical activity to unlock their potential.',
    focusAreas: ['youth-development', 'health', 'education', 'social-justice'],
    partnershipTypes: ['grants', 'sponsorship', 'in_kind', 'employee_giving'],
    givingUrl: 'https://about.nike.com/en/impact',
    headquarters: 'Beaverton, OR',
  },
  {
    name: 'Comcast NBCUniversal Foundation',
    slug: 'comcast-foundation',
    description: 'Supports digital equity, community investment, and next-generation storytellers.',
    focusAreas: ['technology', 'education', 'media-journalism', 'community-development'],
    partnershipTypes: ['grants', 'sponsorship', 'volunteer', 'in_kind'],
    givingUrl: 'https://corporate.comcast.com/impact',
    headquarters: 'Philadelphia, PA',
  },
  {
    name: 'Verizon Foundation',
    slug: 'verizon-foundation',
    description: 'Focuses on digital inclusion, climate protection, and human prosperity through technology.',
    focusAreas: ['technology', 'education', 'environment', 'social-justice'],
    partnershipTypes: ['grants', 'tech_credits', 'volunteer', 'employee_giving'],
    givingUrl: 'https://www.verizon.com/about/responsibility',
    headquarters: 'New York, NY',
  },
  {
    name: 'State Farm Foundation',
    slug: 'state-farm-foundation',
    description: 'Building stronger communities through education, safe neighborhoods, and community development.',
    focusAreas: ['education', 'community-development', 'housing', 'youth-development'],
    partnershipTypes: ['grants', 'sponsorship', 'volunteer', 'employee_giving'],
    givingUrl: 'https://www.statefarm.com/about-us/community-involvement',
    headquarters: 'Bloomington, IL',
  },
  {
    name: 'FedEx Cares',
    slug: 'fedex-cares',
    description: 'Connects people and possibilities through sustainable logistics, economic empowerment, and road safety.',
    focusAreas: ['economic-development', 'environment', 'community-development', 'workforce'],
    partnershipTypes: ['grants', 'volunteer', 'in_kind', 'employee_giving'],
    givingUrl: 'https://www.fedex.com/en-us/about/corporate-responsibility.html',
    headquarters: 'Memphis, TN',
  },
  {
    name: 'Intel Foundation',
    slug: 'intel-foundation',
    description: 'Expands access to technology and STEM education to create a more equitable and sustainable future.',
    focusAreas: ['education', 'technology', 'science-research', 'social-justice'],
    partnershipTypes: ['grants', 'tech_credits', 'volunteer', 'employee_giving'],
    givingUrl: 'https://www.intel.com/content/www/us/en/corporate-responsibility/intel-foundation.html',
    headquarters: 'Santa Clara, CA',
  },

  // -----------------------------------------------------------------------
  // Collaborative Funds & Intermediary Grantmakers
  // -----------------------------------------------------------------------
  {
    name: 'Borealis Philanthropy',
    slug: 'borealis-philanthropy',
    description: 'Intermediary funder managing collaborative funds for racial equity, trans justice, disability rights, and immigrant rights movements. Pools resources from multiple donors.',
    focusAreas: ['social-justice', 'civic-engagement', 'health', 'community-development'],
    partnershipTypes: ['collaborative_fund', 'intermediary', 'grants'],
    givingUrl: 'https://borealisphilanthropy.org',
    headquarters: 'New York, NY',
  },
  {
    name: 'The Audacious Project',
    slug: 'audacious-project',
    description: 'Collaborative philanthropic initiative housed at TED that funds big, bold solutions to the world\'s most urgent challenges. Pools mega-donor resources for transformative scale.',
    focusAreas: ['education', 'health', 'environment', 'social-justice'],
    partnershipTypes: ['collaborative_fund', 'grants'],
    givingUrl: 'https://audaciousproject.org',
    headquarters: 'New York, NY',
  },
  {
    name: 'Blue Meridian Partners',
    slug: 'blue-meridian-partners',
    description: 'Philanthropic intermediary that pools capital from leading philanthropists to invest in scalable solutions for economic mobility. Focuses on systems change.',
    focusAreas: ['economic-development', 'education', 'workforce', 'youth-development'],
    partnershipTypes: ['collaborative_fund', 'intermediary', 'grants'],
    givingUrl: 'https://www.bluemeridian.org',
    headquarters: 'New York, NY',
  },
  {
    name: 'Co-Impact',
    slug: 'co-impact',
    description: 'Global collaborative philanthropy platform funding systems change at scale in education, health, and economic opportunity across the Global South.',
    focusAreas: ['education', 'health', 'economic-development', 'social-justice'],
    partnershipTypes: ['collaborative_fund', 'grants'],
    givingUrl: 'https://www.co-impact.org',
    headquarters: 'Geneva, Switzerland',
  },
  {
    name: 'New Venture Fund',
    slug: 'new-venture-fund',
    description: 'Fiscal sponsor and intermediary funder supporting innovative projects in civic participation, climate solutions, education, and health equity.',
    focusAreas: ['civic-engagement', 'environment', 'education', 'health'],
    partnershipTypes: ['intermediary', 'grants', 'collaborative_fund'],
    givingUrl: 'https://newventurefund.org',
    headquarters: 'Washington, DC',
  },
  {
    name: 'Lever for Change',
    slug: 'lever-for-change',
    description: 'Connects donors with vetted, high-impact nonprofits through large-scale competitions. Affiliated with MacArthur Foundation. Managed $2B+ in funding.',
    focusAreas: ['education', 'economic-development', 'environment', 'social-justice'],
    partnershipTypes: ['intermediary', 'collaborative_fund', 'grants'],
    givingUrl: 'https://www.leverforchange.org',
    headquarters: 'Chicago, IL',
  },
  {
    name: 'Panorama Global',
    slug: 'panorama-global',
    description: 'Social impact platform working at the intersection of philanthropy, government, and civil society to accelerate equitable solutions to global challenges.',
    focusAreas: ['health', 'education', 'international', 'social-justice'],
    partnershipTypes: ['intermediary', 'collaborative_fund', 'grants'],
    givingUrl: 'https://panoramaglobal.org',
    headquarters: 'Seattle, WA',
  },
  {
    name: 'Catalyst Miami',
    slug: 'catalyst-miami',
    description: 'Community-based intermediary developing grassroots leaders and advancing equity through climate resilience, health, and economic justice.',
    focusAreas: ['environment', 'health', 'economic-development', 'civic-engagement'],
    partnershipTypes: ['intermediary', 'grants', 'collaborative_fund'],
    givingUrl: 'https://www.catalystmiami.org',
    headquarters: 'Miami, FL',
  },
  {
    name: 'Emergent Fund',
    slug: 'emergent-fund',
    description: 'Rapid-response collaborative fund supporting communities of color organizing against white supremacy and building inclusive democracy.',
    focusAreas: ['social-justice', 'civic-engagement', 'community-development'],
    partnershipTypes: ['collaborative_fund', 'grants'],
    givingUrl: 'https://www.inthecommunity.co/emergent-fund',
    headquarters: 'National',
  },
  {
    name: 'Libra Foundation',
    slug: 'libra-foundation',
    description: 'Progressive private foundation investing in systems change through criminal justice reform, climate, economic equity, and democracy.',
    focusAreas: ['social-justice', 'environment', 'economic-development', 'civic-engagement'],
    partnershipTypes: ['grants', 'collaborative_fund'],
    givingUrl: 'https://www.librafoundation.org',
    headquarters: 'San Francisco, CA',
  },
]
